### ISSUE TITLE
Add instructions in fiber-example on how to reach the admin

### ISSUE THREAD

**Issue by mbraak** [ridethepony/django-fiber-example#1]
Add instructions in fiber-example on how to reach the admin.

The instructions are of course: add @fiber to the url.

We could add this to the README, or in the fixture data so the user sees the text when he opens the site in his browser.

**Comment by txfyxzzy** [comment]
I can NOT reach the admin by add @fiber to url, it always response 404 as below:
[06/Jan/2017 02:44:13] "GET /@fiber/ HTTP/1.1" 404 1689

Page not found (404)
Request Method:	GET
Request URL:	http://localhost:8081/@fiber/
Raised by:	fiber.views.FiberTemplateView
