### ISSUE TITLE
python setup.py egg_info

### ISSUE THREAD

**Issue by superrandres** [ridethepony/django-fiber-example#8]
django-fiber-0.10.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-huix1s43/django-fiber/setup.py", line 9
        print "You probably want to also tag the version now:"
                                                             ^
    SyntaxError: Missing parentheses in call to 'print'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-huix1s43/django-fiber/

**Comment by jaap3** [comment]
The current released version of Fiber has no Python 3 support. There's a branch you can check out (https://github.com/ridethepony/django-fiber/tree/django1.9) if you are interested in helping us get there ;-).
